#name: push-action-webhooks
#run-name: ${{ github.actor }} pushed a commit
#on: [push]
#jobs:
#  update-webhooks:
#    runs-on: ubuntu-latest
#    steps:
#      - run: >-
#          curl -X POST -H 'Content-type: application/json'
#          --data '{"text":"This is a test!", "sender":"Gubelio"}' "https://discord.com/api/webhooks/1520518388995063818/Kv30_K6keJOU4DRMf6NyMZxM8LI54_YP4lLBp1fIxyUcWSW7iIvbHDuUJg59X2SKBtao/github"

